spring.application.name=pasaporte-backend
jwt.secret=pasaportecomunicacion2024pasaportecomunicacion2024pasaportecomunicacion2024
jwt.token.validity=600
spring.datasource.url=jdbc:h2:./db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.javax.persistence.schema-generation.database.action=update
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=update
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=esquema.sql
# Aplicacion
baseURIOfFrontend=http://localhost:4200/pasaporte
passwordresettoken.expiration=60

spring.mail.host=correo.uma.es
spring.mail.port=587
spring.mail.username=mail@uma.es
spring.mail.password=contrasenia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
